In [5]:
import sys
!{sys.executable} -m pip install tensorflow

  Using cached tensorflow-2.18.0-cp312-cp312-win_amd64.whl.metadata (3.3 kB)
  Using cached tensorflow_intel-2.18.0-cp312-cp312-win_amd64.whl.metadata (4.9 kB)
  Using cached absl_py-2.1.0-py3-none-any.whl.metadata (2.3 kB)
  Using cached astunparse-1.6.3-py2.py3-none-any.whl.metadata (4.4 kB)
  Using cached gast-0.6.0-py3-none-any.whl.metadata (1.3 kB)
  Using cached google_pasta-0.2.0-py3-none-any.whl.metadata (814 bytes)
  Using cached libclang-18.1.1-py2.py3-none-win_amd64.whl.metadata (5.3 kB)
  Using cached opt_einsum-3.4.0-py3-none-any.whl.metadata (6.3 kB)
  Using cached termcolor-2.5.0-py3-none-any.whl.metadata (6.1 kB)
  Using cached grpcio-1.70.0-cp312-cp312-win_amd64.whl.metadata (4.0 kB)
  Using cached tensorboard-2.18.0-py3-none-any.whl.metadata (1.6 kB)
  Using cached keras-3.8.0-py3-none-any.whl.metadata (5.8 kB)
  Using cached ml_dtypes-0.4.1-cp312-cp312-win_amd64.whl.metadata (20 kB)
  Using cached namex-0.0.8-py3-none-any.whl.metadata (246 bytes)
  Using cached optre

In [6]:
import tensorflow as tf

#### Para fazer qualquer coisa no tensorflow é importante que tenhamos tensores criados com alguns valores iniciais

In [8]:
x = tf.ones(shape=(2, 1)) # tensores só com 1s, equivalente a np.ones
x

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[1.],
       [1.]], dtype=float32)>

In [9]:
x = tf.zeros(shape=(2, 1)) # tensores só com 0s, equivalente a np.zeros
x

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[0.],
       [0.]], dtype=float32)>

In [10]:
x = tf.random.normal(shape=(3, 1), mean=0, stddev=1.) # equivalente a np.random.normal
x

<tf.Tensor: shape=(3, 1), dtype=float32, numpy=
array([[ 0.45708665],
       [-1.308673  ],
       [-0.0138353 ]], dtype=float32)>

#### Um tensor normal não pode mudar os valores depois de criado, então usamos o 'tf.Variable' para mudar os valores ao longo do tempo (e é isso que o treinamento de IA faz)
#### Utilizando o .assign(novo_valor) podemos modificar a variável.

In [13]:
v = tf.Variable(tf.random.normal(shape=(3, 1)))
v

<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[ 0.20992804],
       [-0.24937363],
       [-0.2304734 ]], dtype=float32)>

In [14]:
v.assign(tf.ones((3, 1)))
v

<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[1.],
       [1.],
       [1.]], dtype=float32)>

In [15]:
v[0, 0].assign(3.)

<tf.Variable 'UnreadVariable' shape=(3, 1) dtype=float32, numpy=
array([[3.],
       [1.],
       [1.]], dtype=float32)>

#### Operações

In [17]:
a = tf.ones((2,2))
a

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.]], dtype=float32)>

In [18]:
b = tf.square(a)
b

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.]], dtype=float32)>

In [19]:
c = tf.sqrt(a)
c

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.]], dtype=float32)>

In [20]:
d = b + c 
d

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2., 2.],
       [2., 2.]], dtype=float32)>

In [21]:
e = tf.matmul(a, b)
e

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2., 2.],
       [2., 2.]], dtype=float32)>

#### GradientTape é uma ferramenta do TensorFlow para calcular gradientes automaticamente. Ele grava os cálculos dentro do bloco

In [24]:
a = tf.Variable(initial_value=3.)
a

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=3.0>

In [26]:
with tf.GradientTape() as tape:
    result = tf.square(a)

gradiente = tape.gradient(result, a)
print(gradiente)

tf.Tensor(6.0, shape=(), dtype=float32)


#### O TensorFlow por padrão só acompanha variáveis treináveis (tf.Variable). Se tentarmos calcular o gradiente de um tensor constante (tf.constant), ele não acompanha automaticamente, então temos que usar tape.watch

In [28]:
input_const = tf.constant(3.)

with tf.GradientTape() as tape:
 tape.watch(input_const)
 result = tf.square(input_const)
    
gradient = tape.gradient(result, input_const)
print(gradiente)

tf.Tensor(6.0, shape=(), dtype=float32)
